variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: clone

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - grad
  image: gradle:alpine
  script: ./gradlew assemble
  only:
    refs:
      - branches
test:
  stage: test
  tags:
    - grad
  image: gradle:alpine
  script: ./gradlew check
  only:
    refs:
      - branches

deploy-test:
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_TEST_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
  only:
    - develop

deploy-prod:
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
  only:
    - main